# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Vcontrol add-on
version: "1.10.32"
slug: vcontrold
description: Vcontrold add-on
url: "https://github.com/netxxl/homeassistant-vcontrol"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  tty: "/dev/ttyUSB0"
  refresh: 20
  device_id: "2098"
  mqtt_topic: "openv"
  loop_vclient: false
  debug: false
  commands:
    - getTempA:FLOAT
    - getTempWWist:FLOAT
    - getTempWWsoll:FLOAT
    - getTempKist:FLOAT
    - getTempKsoll:FLOAT
    - getTempVListM2:FLOAT 
    - getTempRaumNorSollM2:FLOAT
    - getTempRaumRedSollM2:FLOAT
    - getBrennerStatus:FLOAT
    - getBrennerStarts:FLOAT
    - getBrennerStunden1:FLOAT
    - getBrennerStunden2:FLOAT 
    - getPumpeStatusSp:FLOAT
    - getPumpeStatusZirku:FLOAT
    - getPumpeStatusM2:FLOAT   
    - getMischerM2:FLOAT       
    - getNeigungM2:FLOAT  
    - getNiveauM2:FLOAT
    - getBetriebPartyM2:FLOAT    
    - getBetriebArtM2:FLOAT   
schema:
  tty: "str"
  refresh: "int"
  device_id: "str"
  vcontrol_host: "str?"
  vcontrol_port: "int?"
  mqtt_host: "str?"
  mqtt_port: "int?"
  mqtt_user: "str?"
  mqtt_password: "str?"
  mqtt_topic: "str"
  loop_vclient: "bool?"
  debug: "bool?"
  commands:
    - "str"
# image: "ghcr.io/netxxl/{arch}-homeassistant-vcontrol"
usb: true
apparmor: false
ports:
  3002/tcp: 3002
ports_description:
  3002/tcp: "Vcontrol deamon"
services:
  - mqtt:need
devices:
  - /dev/ttyUSB0
  - /dev/ttyUSB1
  - /dev/ttyUSB2
  - /dev/ttyUSB3
map:
  - config
